name: CI

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
        with:
          determinate: true
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "amarbel-llc/tacky"
          rolling: true
          visibility: "public"
          include-output-paths: true
          directory: ./

  build-nix-package:
    strategy:
      matrix:
        include:
          - os: macos-15
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix build
